'use client';

import { stegaClean } from 'next-sanity';
import { useEffect, useState } from 'react';
import { cn } from '@/lib/utils/index';

type TableOfContentsProps = {
  headings: {
    style: string;
    text: string;
  }[];
  onThisPageLabel?: string;
  className?: string;
};

export default function TableOfContents({
  headings,
  onThisPageLabel,
  className,
}: TableOfContentsProps) {
  const [activeId, setActiveId] = useState<string>('');

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setActiveId(entry.target.id);
          }
        });
      },
      { rootMargin: '-100px 0px -66%' }
    );

    const headingElements = document.querySelectorAll('h2, h3');
    headingElements.forEach((element) => {
      observer.observe(element);
    });

    return () => {
      headingElements.forEach((element) => {
        observer.unobserve(element);
      });
    };
  }, []);

  if (!headings?.length) return null;

  return (
    <nav className={cn('sticky top-24 max-h-[calc(100vh-6rem)] overflow-auto', className)}>
      <h4 className="flex items-center gap-2 mb-4 text-xs font-bold tracking-widest text-muted-foreground uppercase">
        <span className="text-lg">≡</span> {onThisPageLabel || 'On this page'}
      </h4>
      <ul className="space-y-0 text-sm">
        {headings.map((heading, index) => {
          // Create a slug from the heading text to match IDs generated by PortableText
          // This assumes the PortableText renderer generates IDs based on text content
          // If not, we'll need to update the PortableText components to add IDs
          const id = heading.text
            .toLowerCase()
            .replace(/[^\w\s-]/g, '')
            .replace(/\s+/g, '-');

          return (
            <li
              key={index}
              className={cn(
                'relative transition-colors border-l-2',
                stegaClean(heading.style) === 'h3' ? 'pl-6' : 'pl-4',
                activeId === id
                  ? 'border-primary font-medium text-primary'
                  : 'border-transparent text-muted-foreground hover:text-primary hover:border-border'
              )}
            >
              <a
                href={`#${id}`}
                onClick={(e) => {
                  e.preventDefault();
                  document.querySelector(`#${id}`)?.scrollIntoView({
                    behavior: 'smooth',
                  });
                }}
                className="block py-1"
              >
                {heading.text}
              </a>
            </li>
          );
        })}
      </ul>
    </nav>
  );
}
